--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Pedhot-Dev/SkyBlockUI
build-by-default: true
branches:
- master
projects:
  SkyBlockUI:
    path: "https://github.com/Pedhot-Dev/SkyBlockUI/blob/master/image_create.jpg"
...
